{% set name = "confz" %}
{% set version = "2.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/confz-{{ version }}.tar.gz
  sha256: c2d7af28224d8e70c72f66c4ea7ca0069abdc73dda11732d74f2be7dbe8641a0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7.2,<4.0
  run:
    - pydantic >=1.9.0,<3.0.0
    - python >=3.7.2,<4.0
    - python-dotenv >=0.19.2,<2.0.0
    - pyyaml >=5.4.1,<7.0.0
    - toml >=0.10.2,<0.11.0

test:
  imports:
    - confz
    - confz.loaders
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Zuehlke/ConfZ
  doc_url: https://confz.readthedocs.io/
  summary: A configuration management library for Python based on pydantic.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
