{% set name = "confz" %}
{% set version = "1.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/confz-{{ version }}.tar.gz
  sha256: bbdae174a100eebb63f021804d5e8e9ef6296d31ee639994c6eb8267b83462e5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7,<4.0
  run:
    - pydantic >=1.9.0,<2.0.0
    - python >=3.7,<4.0
    - python-dotenv >=0.19.2,<0.20.0
    - pyyaml >=5.4.1,<7.0.0
    - toml >=0.10.2

test:
  imports:
    - confz
    - confz.loaders
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Zuehlke/ConfZ
  doc_url: https://confz.readthedocs.io/
  summary: A configuration management library for Python based on pydantic.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
