{% set name = "confz" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/confz-{{ version }}.tar.gz
  sha256: 9bba65610084c207fd054590d2179cf5c98f7943c921a7a211b91d71da966b2a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - pydantic >=1.9.0,<3.0.0
    - python >={{ python_min }},<4.0
    - python-dotenv >=0.19.2,<2.0.0
    - pyyaml >=5.4.1,<7.0.0
    - toml >=0.10.2,<0.11.0

test:
  imports:
    - confz
    - confz.loaders
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Zuehlke/ConfZ
  doc_url: https://confz.readthedocs.io/
  summary: A configuration management library for Python based on pydantic.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
